// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Application_Status int32

const (
	// application doesn't have this status
	// any application with this status - is not correct
	Application_APPLICATION_STATUS_UNSPECIFIED Application_Status = 0
	Application_APPLICATION_STATUS_OPEN        Application_Status = 1
	Application_APPLICATION_STATUS_IN_PROGRESS Application_Status = 2
	Application_APPLICATION_STATUS_CLOSED      Application_Status = 3
)

var Application_Status_name = map[int32]string{
	0: "APPLICATION_STATUS_UNSPECIFIED",
	1: "APPLICATION_STATUS_OPEN",
	2: "APPLICATION_STATUS_IN_PROGRESS",
	3: "APPLICATION_STATUS_CLOSED",
}

var Application_Status_value = map[string]int32{
	"APPLICATION_STATUS_UNSPECIFIED": 0,
	"APPLICATION_STATUS_OPEN":        1,
	"APPLICATION_STATUS_IN_PROGRESS": 2,
	"APPLICATION_STATUS_CLOSED":      3,
}

func (x Application_Status) String() string {
	return proto.EnumName(Application_Status_name, int32(x))
}

func (Application_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{7, 0}
}

type Application_ExternalStatus int32

const (
	// application doesn't have this status
	// any application with this status - is not correct
	Application_APPLICATION_EXTERNAL_STATUS_UNSPECIFIED Application_ExternalStatus = 0
	Application_APPLICATION_EXTERNAL_STATUS_PROCESSED   Application_ExternalStatus = 1
	Application_APPLICATION_EXTERNAL_STATUS_SKIPPED     Application_ExternalStatus = 2
)

var Application_ExternalStatus_name = map[int32]string{
	0: "APPLICATION_EXTERNAL_STATUS_UNSPECIFIED",
	1: "APPLICATION_EXTERNAL_STATUS_PROCESSED",
	2: "APPLICATION_EXTERNAL_STATUS_SKIPPED",
}

var Application_ExternalStatus_value = map[string]int32{
	"APPLICATION_EXTERNAL_STATUS_UNSPECIFIED": 0,
	"APPLICATION_EXTERNAL_STATUS_PROCESSED":   1,
	"APPLICATION_EXTERNAL_STATUS_SKIPPED":     2,
}

func (x Application_ExternalStatus) String() string {
	return proto.EnumName(Application_ExternalStatus_name, int32(x))
}

func (Application_ExternalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{7, 1}
}

type GetApplicationByIdRequestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationByIdRequestRequest) Reset()         { *m = GetApplicationByIdRequestRequest{} }
func (m *GetApplicationByIdRequestRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationByIdRequestRequest) ProtoMessage()    {}
func (*GetApplicationByIdRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{0}
}

func (m *GetApplicationByIdRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationByIdRequestRequest.Unmarshal(m, b)
}
func (m *GetApplicationByIdRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationByIdRequestRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationByIdRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationByIdRequestRequest.Merge(m, src)
}
func (m *GetApplicationByIdRequestRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationByIdRequestRequest.Size(m)
}
func (m *GetApplicationByIdRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationByIdRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationByIdRequestRequest proto.InternalMessageInfo

func (m *GetApplicationByIdRequestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetApplicationsByFiltersRequest struct {
	Status               Application_Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.Application_Status" json:"status,omitempty"`
	CreatedAtTimerange   *TimeRange         `protobuf:"bytes,2,opt,name=created_at_timerange,json=createdAtTimerange,proto3" json:"created_at_timerange,omitempty"`
	UpdatedAtTimerange   *TimeRange         `protobuf:"bytes,3,opt,name=updated_at_timerange,json=updatedAtTimerange,proto3" json:"updated_at_timerange,omitempty"`
	UserId               string             `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetApplicationsByFiltersRequest) Reset()         { *m = GetApplicationsByFiltersRequest{} }
func (m *GetApplicationsByFiltersRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationsByFiltersRequest) ProtoMessage()    {}
func (*GetApplicationsByFiltersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{1}
}

func (m *GetApplicationsByFiltersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationsByFiltersRequest.Unmarshal(m, b)
}
func (m *GetApplicationsByFiltersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationsByFiltersRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationsByFiltersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationsByFiltersRequest.Merge(m, src)
}
func (m *GetApplicationsByFiltersRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationsByFiltersRequest.Size(m)
}
func (m *GetApplicationsByFiltersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationsByFiltersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationsByFiltersRequest proto.InternalMessageInfo

func (m *GetApplicationsByFiltersRequest) GetStatus() Application_Status {
	if m != nil {
		return m.Status
	}
	return Application_APPLICATION_STATUS_UNSPECIFIED
}

func (m *GetApplicationsByFiltersRequest) GetCreatedAtTimerange() *TimeRange {
	if m != nil {
		return m.CreatedAtTimerange
	}
	return nil
}

func (m *GetApplicationsByFiltersRequest) GetUpdatedAtTimerange() *TimeRange {
	if m != nil {
		return m.UpdatedAtTimerange
	}
	return nil
}

func (m *GetApplicationsByFiltersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TimeRange struct {
	Start                *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{2}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStart() *timestamppb.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *TimeRange) GetEnd() *timestamppb.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

type GetApplicationsByFiltersResponse struct {
	Applications         []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetApplicationsByFiltersResponse) Reset()         { *m = GetApplicationsByFiltersResponse{} }
func (m *GetApplicationsByFiltersResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationsByFiltersResponse) ProtoMessage()    {}
func (*GetApplicationsByFiltersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{3}
}

func (m *GetApplicationsByFiltersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationsByFiltersResponse.Unmarshal(m, b)
}
func (m *GetApplicationsByFiltersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationsByFiltersResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationsByFiltersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationsByFiltersResponse.Merge(m, src)
}
func (m *GetApplicationsByFiltersResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationsByFiltersResponse.Size(m)
}
func (m *GetApplicationsByFiltersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationsByFiltersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationsByFiltersResponse proto.InternalMessageInfo

func (m *GetApplicationsByFiltersResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type UpdateApplicationRequest struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Application_Status `protobuf:"varint,2,opt,name=status,proto3,enum=api.Application_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateApplicationRequest) Reset()         { *m = UpdateApplicationRequest{} }
func (m *UpdateApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateApplicationRequest) ProtoMessage()    {}
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{4}
}

func (m *UpdateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateApplicationRequest.Unmarshal(m, b)
}
func (m *UpdateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApplicationRequest.Merge(m, src)
}
func (m *UpdateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateApplicationRequest.Size(m)
}
func (m *UpdateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApplicationRequest proto.InternalMessageInfo

func (m *UpdateApplicationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateApplicationRequest) GetStatus() Application_Status {
	if m != nil {
		return m.Status
	}
	return Application_APPLICATION_STATUS_UNSPECIFIED
}

type CreateApplicationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateApplicationRequest) Reset()         { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()    {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{5}
}

func (m *CreateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationRequest.Unmarshal(m, b)
}
func (m *CreateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationRequest.Merge(m, src)
}
func (m *CreateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationRequest.Size(m)
}
func (m *CreateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationRequest proto.InternalMessageInfo

func (m *CreateApplicationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetApplicationByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationByIdRequest) Reset()         { *m = GetApplicationByIdRequest{} }
func (m *GetApplicationByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationByIdRequest) ProtoMessage()    {}
func (*GetApplicationByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{6}
}

func (m *GetApplicationByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationByIdRequest.Unmarshal(m, b)
}
func (m *GetApplicationByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationByIdRequest.Merge(m, src)
}
func (m *GetApplicationByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationByIdRequest.Size(m)
}
func (m *GetApplicationByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationByIdRequest proto.InternalMessageInfo

func (m *GetApplicationByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Application struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Application_Status         `protobuf:"varint,2,opt,name=status,proto3,enum=api.Application_Status" json:"status,omitempty"`
	UserId               string                     `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExternalStatus       Application_ExternalStatus `protobuf:"varint,6,opt,name=external_status,json=externalStatus,proto3,enum=api.Application_ExternalStatus" json:"external_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{7}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetStatus() Application_Status {
	if m != nil {
		return m.Status
	}
	return Application_APPLICATION_STATUS_UNSPECIFIED
}

func (m *Application) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Application) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Application) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Application) GetExternalStatus() Application_ExternalStatus {
	if m != nil {
		return m.ExternalStatus
	}
	return Application_APPLICATION_EXTERNAL_STATUS_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("api.Application_Status", Application_Status_name, Application_Status_value)
	proto.RegisterEnum("api.Application_ExternalStatus", Application_ExternalStatus_name, Application_ExternalStatus_value)
	proto.RegisterType((*GetApplicationByIdRequestRequest)(nil), "api.GetApplicationByIdRequestRequest")
	proto.RegisterType((*GetApplicationsByFiltersRequest)(nil), "api.GetApplicationsByFiltersRequest")
	proto.RegisterType((*TimeRange)(nil), "api.TimeRange")
	proto.RegisterType((*GetApplicationsByFiltersResponse)(nil), "api.GetApplicationsByFiltersResponse")
	proto.RegisterType((*UpdateApplicationRequest)(nil), "api.UpdateApplicationRequest")
	proto.RegisterType((*CreateApplicationRequest)(nil), "api.CreateApplicationRequest")
	proto.RegisterType((*GetApplicationByIdRequest)(nil), "api.GetApplicationByIdRequest")
	proto.RegisterType((*Application)(nil), "api.Application")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor_fc846aced8fe6ea6) }

var fileDescriptor_fc846aced8fe6ea6 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x4e, 0xdb, 0x4c,
	0x10, 0xc7, 0xb1, 0x03, 0xf9, 0x3e, 0x26, 0x55, 0x1a, 0x56, 0x95, 0x62, 0x52, 0x01, 0x91, 0x5b,
	0x04, 0x15, 0x95, 0x53, 0x99, 0x5e, 0xb8, 0xd5, 0x49, 0x0c, 0xb2, 0x8a, 0x12, 0x6b, 0x6d, 0x24,
	0x6e, 0xd6, 0x82, 0xb7, 0xd1, 0xaa, 0x21, 0x76, 0xed, 0x0d, 0x2a, 0xd7, 0x9e, 0x7b, 0xe9, 0xa3,
	0xf5, 0x05, 0xfa, 0x0a, 0xbd, 0xf7, 0x54, 0x79, 0xe3, 0x24, 0x0e, 0xb6, 0xc3, 0xa5, 0xa7, 0x38,
	0xde, 0xdf, 0xcc, 0xce, 0xfc, 0xe7, 0xef, 0x81, 0x1d, 0x12, 0x86, 0x63, 0x76, 0x4b, 0x38, 0x0b,
	0x26, 0x5a, 0x18, 0x05, 0x3c, 0x40, 0x15, 0x12, 0xb2, 0xd6, 0xc1, 0x28, 0x08, 0x46, 0x63, 0xda,
	0x11, 0xaf, 0x6e, 0xa6, 0x9f, 0x3a, 0x9c, 0xdd, 0xd1, 0x98, 0x93, 0xbb, 0x70, 0x46, 0xb5, 0x9a,
	0xf7, 0x64, 0xcc, 0x7c, 0xc2, 0x69, 0x67, 0xfe, 0x30, 0x3b, 0x50, 0x75, 0x68, 0x5f, 0x50, 0x6e,
	0x2c, 0xd3, 0x76, 0x1f, 0x2c, 0x1f, 0xd3, 0x2f, 0x53, 0x1a, 0xf3, 0xf4, 0x07, 0xd5, 0x41, 0x66,
	0xbe, 0x22, 0xb5, 0xa5, 0xe3, 0x6d, 0x2c, 0x33, 0x5f, 0xfd, 0x2d, 0xc1, 0xc1, 0x6a, 0x50, 0xdc,
	0x7d, 0x38, 0x67, 0x63, 0x4e, 0xa3, 0x78, 0x1e, 0xd3, 0x81, 0x6a, 0xcc, 0x09, 0x9f, 0xc6, 0x22,
	0xae, 0xae, 0x37, 0x35, 0x12, 0x32, 0x2d, 0x13, 0xa2, 0x39, 0xe2, 0x18, 0xa7, 0x18, 0xfa, 0x00,
	0x2f, 0x6e, 0x23, 0x4a, 0x38, 0xf5, 0x3d, 0xc2, 0xbd, 0xa4, 0xfe, 0x88, 0x4c, 0x46, 0x54, 0x91,
	0xdb, 0xd2, 0x71, 0x4d, 0xaf, 0x8b, 0x70, 0x97, 0xdd, 0x51, 0x9c, 0xbc, 0xc5, 0x28, 0x65, 0x0d,
	0xee, 0xce, 0xc9, 0x24, 0xc3, 0x34, 0xf4, 0xf3, 0x19, 0x2a, 0xc5, 0x19, 0x52, 0x36, 0x9b, 0xa1,
	0x09, 0xff, 0x4d, 0x63, 0x1a, 0x79, 0xcc, 0x57, 0x36, 0x45, 0xb7, 0xd5, 0xe4, 0xaf, 0xe5, 0xab,
	0x9f, 0x61, 0x7b, 0x11, 0x89, 0xde, 0xc1, 0x56, 0xcc, 0x49, 0xc4, 0x45, 0x67, 0x35, 0xbd, 0xa5,
	0xcd, 0xc4, 0xd7, 0xe6, 0xe2, 0x8b, 0x4b, 0x84, 0xf8, 0x78, 0x06, 0xa2, 0xb7, 0x50, 0xa1, 0x13,
	0x3f, 0x6d, 0x65, 0x1d, 0x9f, 0x60, 0xea, 0xf5, 0xe3, 0x91, 0x64, 0xd5, 0x8d, 0xc3, 0x60, 0x12,
	0x53, 0xf4, 0x1e, 0x9e, 0x65, 0xac, 0x90, 0x88, 0x5c, 0x39, 0xae, 0xe9, 0x8d, 0xc7, 0x22, 0xe3,
	0x15, 0x4a, 0xa5, 0xa0, 0x5c, 0x89, 0xae, 0xb3, 0x48, 0xf1, 0x90, 0xd1, 0xd9, 0x62, 0x80, 0xf2,
	0xda, 0x01, 0x76, 0xff, 0xff, 0xd3, 0xdd, 0xfa, 0x26, 0xc9, 0xed, 0x8d, 0xf9, 0x28, 0xd5, 0x53,
	0x50, 0x7a, 0x62, 0x3c, 0x05, 0xd7, 0x64, 0x24, 0x96, 0x56, 0x24, 0x3e, 0x81, 0xdd, 0x52, 0x23,
	0xe6, 0x1c, 0xf8, 0x6b, 0x13, 0x6a, 0x19, 0xf4, 0x1f, 0x16, 0x9f, 0x2d, 0xb0, 0x92, 0x2d, 0x10,
	0x9d, 0x01, 0x2c, 0x0d, 0x2a, 0xfc, 0xb1, 0x7e, 0x96, 0xdb, 0x0b, 0x8b, 0x26, 0xa1, 0x4b, 0x67,
	0x2a, 0x5b, 0x4f, 0x87, 0x2e, 0xbc, 0x89, 0x30, 0x3c, 0xa7, 0x5f, 0x39, 0x8d, 0x26, 0x64, 0xec,
	0xa5, 0x2d, 0x55, 0x45, 0x4b, 0x07, 0xb9, 0x96, 0xcc, 0x94, 0xcb, 0xb5, 0x56, 0xa7, 0x2b, 0x27,
	0xea, 0x77, 0x09, 0xaa, 0xb3, 0x47, 0xa4, 0xc2, 0xbe, 0x61, 0xdb, 0x97, 0x56, 0xcf, 0x70, 0xad,
	0xe1, 0xc0, 0x73, 0x5c, 0xc3, 0xbd, 0x72, 0xbc, 0xab, 0x81, 0x63, 0x9b, 0x3d, 0xeb, 0xdc, 0x32,
	0xfb, 0x8d, 0x0d, 0xf4, 0x12, 0x9a, 0x05, 0xcc, 0xd0, 0x36, 0x07, 0x0d, 0xa9, 0x24, 0x81, 0x35,
	0xf0, 0x6c, 0x3c, 0xbc, 0xc0, 0xa6, 0xe3, 0x34, 0x64, 0xb4, 0x07, 0xbb, 0x05, 0x4c, 0xef, 0x72,
	0xe8, 0x98, 0xfd, 0x46, 0x45, 0xfd, 0x21, 0x41, 0x7d, 0xb5, 0x76, 0x74, 0x02, 0x47, 0xd9, 0x08,
	0xf3, 0xda, 0x35, 0xf1, 0xc0, 0xb8, 0x2c, 0xae, 0xef, 0x0d, 0x1c, 0xae, 0x83, 0x6d, 0x3c, 0xec,
	0x99, 0x4e, 0x72, 0x95, 0x84, 0x8e, 0xe0, 0xd5, 0x3a, 0xd4, 0xf9, 0x68, 0xd9, 0xb6, 0xd9, 0x6f,
	0xc8, 0xfa, 0x4f, 0x19, 0x50, 0x46, 0x5b, 0x87, 0x46, 0xf7, 0xec, 0x96, 0xa2, 0x3e, 0xec, 0xe4,
	0x9c, 0x8d, 0xf6, 0xc4, 0x24, 0xca, 0x1c, 0xdf, 0xca, 0x7d, 0x94, 0xe8, 0x1c, 0x50, 0xde, 0xea,
	0x68, 0x5f, 0x70, 0xa5, 0xdf, 0x40, 0x41, 0x9e, 0x11, 0x28, 0x65, 0x8b, 0x02, 0xbd, 0x2e, 0xc8,
	0x96, 0xdb, 0xd2, 0xad, 0xc3, 0x27, 0xa8, 0x74, 0xdb, 0xf4, 0x61, 0x27, 0xb7, 0x37, 0xd2, 0xb6,
	0xcb, 0xf6, 0x49, 0xbe, 0xdc, 0x9b, 0xaa, 0x70, 0xfa, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0xda, 0x82, 0x7f, 0xc5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationServiceClient interface {
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	GetApplicationById(ctx context.Context, in *GetApplicationByIdRequest, opts ...grpc.CallOption) (*Application, error)
	GetApplicationsByFilters(ctx context.Context, in *GetApplicationsByFiltersRequest, opts ...grpc.CallOption) (*GetApplicationsByFiltersResponse, error)
	UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
}

type applicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewApplicationServiceClient(cc *grpc.ClientConn) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, "/api.ApplicationService/CreateApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationById(ctx context.Context, in *GetApplicationByIdRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, "/api.ApplicationService/GetApplicationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationsByFilters(ctx context.Context, in *GetApplicationsByFiltersRequest, opts ...grpc.CallOption) (*GetApplicationsByFiltersResponse, error) {
	out := new(GetApplicationsByFiltersResponse)
	err := c.cc.Invoke(ctx, "/api.ApplicationService/GetApplicationsByFilters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, "/api.ApplicationService/UpdateApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServiceServer is the server API for ApplicationService service.
type ApplicationServiceServer interface {
	CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error)
	GetApplicationById(context.Context, *GetApplicationByIdRequest) (*Application, error)
	GetApplicationsByFilters(context.Context, *GetApplicationsByFiltersRequest) (*GetApplicationsByFiltersResponse, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error)
}

// UnimplementedApplicationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedApplicationServiceServer struct {
}

func (*UnimplementedApplicationServiceServer) CreateApplication(ctx context.Context, req *CreateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplication not implemented")
}
func (*UnimplementedApplicationServiceServer) GetApplicationById(ctx context.Context, req *GetApplicationByIdRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationById not implemented")
}
func (*UnimplementedApplicationServiceServer) GetApplicationsByFilters(ctx context.Context, req *GetApplicationsByFiltersRequest) (*GetApplicationsByFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationsByFilters not implemented")
}
func (*UnimplementedApplicationServiceServer) UpdateApplication(ctx context.Context, req *UpdateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplication not implemented")
}

func RegisterApplicationServiceServer(s *grpc.Server, srv ApplicationServiceServer) {
	s.RegisterService(&_ApplicationService_serviceDesc, srv)
}

func _ApplicationService_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApplicationService/CreateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApplicationService/GetApplicationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationById(ctx, req.(*GetApplicationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationsByFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationsByFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationsByFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApplicationService/GetApplicationsByFilters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationsByFilters(ctx, req.(*GetApplicationsByFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpdateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpdateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApplicationService/UpdateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpdateApplication(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplication",
			Handler:    _ApplicationService_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplicationById",
			Handler:    _ApplicationService_GetApplicationById_Handler,
		},
		{
			MethodName: "GetApplicationsByFilters",
			Handler:    _ApplicationService_GetApplicationsByFilters_Handler,
		},
		{
			MethodName: "UpdateApplication",
			Handler:    _ApplicationService_UpdateApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}
